pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git url: 'https://github.com/Er-Diwakar/java-ci-cd-demo.git'
            }
        }

        stage('Build with Maven') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t java-ci-app:1.0 .'
            }
        }

        stage('Run App') {
            steps {
                sh 'docker run --rm java-ci-app:1.0'
            }
        }
    }
}
